apply_chat_template: true
beta: 10
bf16: true
chosen_key: 2_sections
dataset: scottgeng00/delta_learning_num_sections_3section_tied
dataset_probs: 1.0
dpo_loss_type: dpo_norm
flash_attn: true
gradient_checkpointing: true
l2: 0
learning_rate: 1e-7
load_checkpoint: true
lr_scheduler: cosine_with_min_lr
lr_warmup_ratio: 0.03
max_ckpt_num: 1
max_epochs: 1
max_len: 2048
max_samples: 16384
micro_train_batch_size: 1
nll_loss_coef: 0
pretrain: meta-llama/Llama-3.2-3B-Instruct
rejected_key: 3_sections
save_path: exp_num_sections/llama-3.2-3b-instruct_dpo_chosen-2-sections_rejected-3-sections
save_steps: 40
train_batch_size: 32
train_split: train
use_wandb: 'yes'
wandb_project: openrlhf_train_dpo
zero_stage: 1
