apply_chat_template: true
beta: 5
bf16: true
chosen_key: chosen
dataset: scottgeng00/delta_learning_ufweak
dataset_probs: 1.0
dpo_loss_type: dpo_norm
flash_attn: true
gradient_checkpointing: true
l2: 0
learning_rate: 7e-8
load_checkpoint: true
lr_scheduler: cosine_with_min_lr
lr_warmup_ratio: 0.03
max_ckpt_num: 1
max_epochs: 1
max_len: 2048
micro_train_batch_size: 1
nll_loss_coef: 0
pretrain: meta-llama/Llama-3.1-8B-Instruct
rejected_key: rejected
save_path: exp_ultrafeedback_weak/llama-3.1-8b-instruct_dpo
save_steps: 40
train_batch_size: 32
train_split: train
use_wandb: 'yes'
wandb_project: openrlhf_train_dpo
zero_stage: 1
